auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Beetaa.com
url: http://beetaa.com
feed: /atom.xml
author_info: <a href="http://beetaa.com/">Beetaa</a>

media_url: http://blog-media.qiniudn.com/
